Hammox.defmock(RintoPMO.ActorsMock, for: RintoPMO.Actors.Behaviour)
Hammox.defmock(RintoPMO.AnnotationsMock, for: RintoPMO.Annotations.Behaviour)
Hammox.defmock(RintoPMO.AttachmentsMock, for: RintoPMO.Attachments.Behaviour)
Hammox.defmock(RintoPMO.DocumentsMock, for: RintoPMO.Documents.Behaviour)
Hammox.defmock(RintoPMO.ProjectsMock, for: RintoPMO.Projects.Behaviour)
Hammox.defmock(RintoPMO.RepoCredentialsMock, for: RintoPMO.RepoCredentials.Behaviour)
Hammox.defmock(RintoPMO.OSProcessMock, for: RintoPMO.OSProcess.Behaviour)
Hammox.defmock(RintoPMO.Agent.RpcMock, for: RintoPMO.Agent.Rpc.Behaviour)
